### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by dchatzoglou** [emergenzeHack/covid19italia#521] opened 2020-04-15 08:42 UTC
I have copy-pasted and translated from the Italian branch the searchissues.html, search.js and search.min.js files. When you search on the gr branch, we have no results.
![image](https://user-images.githubusercontent.com/62565862/79317234-22e62800-7f0e-11ea-8b45-c44d15a67bcb.png)

**Comment by mfortini** [comment] 2020-04-15 10:38
I translated search terms. I believe we need to update lunr to get utf-8 search

**Comment by iltempe** [comment] 2020-04-15 11:12
duplicate of #522 . I close.

**Closed by iltempe** 2020-04-15 11:12 UTC
Labels: bug, gr branch, international
